export type TrackSkillFilter = {
  id: string;
  label: string;
  keywords: string[];
};

export const TRACK_SKILL_MAP: Record<string, TrackSkillFilter[]> = {
  frontend: [
    {
      id: "js",
      label: "JavaScript",
      keywords: ["javascript", "js", "ecmascript", "es6", "es2015", "node", "npm"],
    },
    {
      id: "ts",
      label: "TypeScript",
      keywords: ["typescript", "ts", "типскрипт"],
    },
    {
      id: "react",
      label: "React",
      keywords: [
        "react",
        "jsx",
        "hooks",
        "useeffect",
        "usestate",
        "redux",
        "context",
        "next",
        "nextjs",
      ],
    },
    {
      id: "htmlcss",
      label: "HTML/CSS",
      keywords: [
        "html",
        "css",
        "flex",
        "grid",
        "layout",
        "верстк",
        "адаптив",
        "sass",
        "scss",
        "bem",
        "бэм",
      ],
    },
    {
      id: "browser",
      label: "Browser/DOM",
      keywords: [
        "dom",
        "bom",
        "window",
        "document",
        "event loop",
        "eventloop",
        "рендер",
        "render",
        "reflow",
        "repaint",
        "layout thrash",
        "browser",
        "браузер",
        "v8",
      ],
    },
    {
      id: "async",
      label: "Async/Networking",
      keywords: [
        "promise",
        "async",
        "await",
        "microtask",
        "macrotask",
        "fetch",
        "xhr",
        "http",
        "cors",
        "websocket",
        "ws",
      ],
    },
    {
      id: "perf",
      label: "Performance",
      keywords: [
        "performance",
        "оптимизац",
        "profil",
        "lazy",
        "memo",
        "виртуализац",
        "bundle size",
        "lighthouse",
      ],
    },
    {
      id: "testing",
      label: "Testing",
      keywords: [
        "test",
        "testing",
        "jest",
        "vitest",
        "cypress",
        "playwright",
        "rtl",
        "react testing library",
        "unit",
        "e2e",
      ],
    },
    {
      id: "tooling",
      label: "Tooling",
      keywords: [
        "webpack",
        "vite",
        "rollup",
        "babel",
        "eslint",
        "prettier",
        "tsconfig",
        "bundl",
        "module federation",
      ],
    },
    {
      id: "arch",
      label: "Architecture",
      keywords: [
        "архитектур",
        "паттерн",
        "solid",
        "oop",
        "mvc",
        "clean",
        "ddd",
        "layer",
        "компонент",
        "design system",
        "дизайн-систем",
      ],
    },
  ],
  java: [
    {
      id: "core",
      label: "Core Java",
      keywords: [
        "java",
        "oop",
        "класс",
        "интерфейс",
        "наслед",
        "generics",
        "дженерик",
        "equals",
        "hashcode",
      ],
    },
    {
      id: "collections",
      label: "Collections",
      keywords: ["arraylist", "linkedlist", "hashmap", "map", "set", "list", "коллекц"],
    },
    {
      id: "concurrency",
      label: "Concurrency",
      keywords: [
        "thread",
        "поток",
        "synchronized",
        "volatile",
        "lock",
        "executor",
        "future",
        "deadlock",
        "race",
        "конкурент",
      ],
    },
    {
      id: "jvm",
      label: "JVM/Memory",
      keywords: [
        "jvm",
        "gc",
        "garbage",
        "heap",
        "stack",
        "classloader",
        "jmm",
        "memory",
        "памят",
      ],
    },
    {
      id: "spring",
      label: "Spring",
      keywords: [
        "spring",
        "spring boot",
        "springboot",
        "di",
        "ioc",
        "bean",
        "aop",
        "mvc",
        "hibernate",
        "jpa",
      ],
    },
    {
      id: "sql",
      label: "SQL/DB",
      keywords: [
        "sql",
        "jdbc",
        "postgres",
        "mysql",
        "index",
        "индекс",
        "join",
        "нормализац",
        "database",
        "бд",
      ],
    },
    {
      id: "tx",
      label: "Transactions",
      keywords: [
        "acid",
        "transaction",
        "изоляц",
        "lock",
        "mvcc",
        "commit",
        "rollback",
        "транзакц",
      ],
    },
    {
      id: "micro",
      label: "Microservices",
      keywords: [
        "microservice",
        "микросервис",
        "rest",
        "grpc",
        "kafka",
        "rabbit",
        "message",
        "saga",
        "event",
      ],
    },
    {
      id: "testing",
      label: "Testing",
      keywords: [
        "junit",
        "mockito",
        "integration test",
        "testcontainers",
        "tdd",
        "unit test",
      ],
    },
    {
      id: "patterns",
      label: "Patterns",
      keywords: [
        "pattern",
        "паттерн",
        "solid",
        "design pattern",
        "factory",
        "singleton",
        "strategy",
        "adapter",
      ],
    },
  ],
  python: [
    {
      id: "core",
      label: "Core Python",
      keywords: [
        "python",
        "тип",
        "list",
        "dict",
        "tuple",
        "set",
        "str",
        "bytes",
        "иттератор",
        "iterator",
        "генератор",
        "generator",
      ],
    },
    {
      id: "oop",
      label: "OOP/Classes",
      keywords: ["oop", "класс", "наслед", "magic method", "dunder", "__init__", "dataclass"],
    },
    {
      id: "async",
      label: "Async",
      keywords: ["async", "await", "asyncio", "event loop", "aiohttp", "celery", "rq"],
    },
    {
      id: "web",
      label: "Web (Django/FastAPI)",
      keywords: [
        "django",
        "fastapi",
        "flask",
        "rest",
        "drf",
        "uvicorn",
        "gunicorn",
        "middleware",
      ],
    },
    {
      id: "db",
      label: "DB/ORM",
      keywords: ["sql", "postgres", "mysql", "sqlite", "orm", "sqlalchemy", "migration", "alembic"],
    },
    {
      id: "testing",
      label: "Testing",
      keywords: ["pytest", "unittest", "mock", "parametrize", "fixture", "coverage"],
    },
    {
      id: "perf",
      label: "Performance",
      keywords: ["gil", "profil", "cprofile", "memory", "perf", "оптимизац"],
    },
    {
      id: "data",
      label: "Data/ETL",
      keywords: ["pandas", "numpy", "etl", "csv", "parquet", "dataframe", "spark"],
    },
    {
      id: "packaging",
      label: "Packaging",
      keywords: [
        "pip",
        "poetry",
        "venv",
        "virtualenv",
        "requirements",
        "wheel",
        "setuptools",
      ],
    },
    {
      id: "devops",
      label: "Deploy/Docker",
      keywords: ["docker", "kubernetes", "k8s", "ci", "cd", "compose"],
    },
  ],
  golang: [
    {
      id: "core",
      label: "Core Go",
      keywords: ["go", "golang", "package", "module", "interface", "struct", "pointer", "slice", "map"],
    },
    {
      id: "concurrency",
      label: "Goroutines/Channels",
      keywords: [
        "goroutine",
        "горутина",
        "channel",
        "канал",
        "select",
        "mutex",
        "waitgroup",
        "race",
      ],
    },
    {
      id: "context",
      label: "Context/Errors",
      keywords: ["context", "cancel", "timeout", "deadline", "error", "panic", "recover", "defer"],
    },
    {
      id: "net",
      label: "Networking",
      keywords: ["http", "tcp", "udp", "grpc", "protobuf", "net", "server", "client"],
    },
    {
      id: "db",
      label: "DB",
      keywords: ["sql", "postgres", "mysql", "gorm", "transaction", "индекс"],
    },
    {
      id: "testing",
      label: "Testing",
      keywords: ["testing", "go test", "mock", "benchmark", "race detector"],
    },
    {
      id: "perf",
      label: "Performance",
      keywords: ["pprof", "profil", "memory", "alloc", "optimization"],
    },
    {
      id: "micro",
      label: "Microservices",
      keywords: ["microservice", "rest", "grpc", "kafka", "rabbit", "queue"],
    },
    {
      id: "tooling",
      label: "Tooling",
      keywords: ["gomod", "go mod", "lint", "golangci-lint", "dep"],
    },
  ],
  backend: [
    {
      id: "api",
      label: "API",
      keywords: ["api", "rest", "graphql", "rpc", "grpc", "http"],
    },
    {
      id: "db",
      label: "Databases",
      keywords: ["sql", "postgres", "mysql", "mongodb", "redis", "index", "transaction", "acid", "бд"],
    },
    {
      id: "arch",
      label: "Architecture",
      keywords: ["архитектур", "монолит", "микросервис", "ddd", "clean", "solid", "паттерн"],
    },
    {
      id: "auth",
      label: "Auth/Security",
      keywords: ["auth", "jwt", "oauth", "oidc", "csrf", "xss", "security", "шифр"],
    },
    {
      id: "cache",
      label: "Cache",
      keywords: ["cache", "кэш", "redis", "memcached"],
    },
    {
      id: "queues",
      label: "Queues/Streaming",
      keywords: ["queue", "очеред", "kafka", "rabbit", "nats", "sqs", "pubsub"],
    },
    {
      id: "observ",
      label: "Observability",
      keywords: [
        "logging",
        "log",
        "metrics",
        "monitor",
        "tracing",
        "prometheus",
        "grafana",
        "opentelemetry",
      ],
    },
    {
      id: "scaling",
      label: "Reliability/Scaling",
      keywords: [
        "load",
        "highload",
        "балансир",
        "retry",
        "circuit",
        "rate limit",
        "идемпотент",
        "slo",
        "sla",
      ],
    },
  ],
  php: [
    {
      id: "core",
      label: "Core PHP",
      keywords: ["php", "тип", "array", "oop", "composer", "namespace", "trait", "autoload"],
    },
    {
      id: "laravel",
      label: "Laravel",
      keywords: ["laravel", "eloquent", "artisan", "middleware", "blade", "sanctum"],
    },
    {
      id: "symfony",
      label: "Symfony",
      keywords: ["symfony", "doctrine", "bundle", "service container", "twig"],
    },
    {
      id: "db",
      label: "DB/SQL",
      keywords: ["sql", "mysql", "postgres", "index", "transaction", "orm", "migration"],
    },
    {
      id: "http",
      label: "HTTP/API",
      keywords: ["http", "rest", "api", "cors", "cookie", "session"],
    },
    {
      id: "testing",
      label: "Testing",
      keywords: ["phpunit", "pest", "mockery", "tdd", "unit test"],
    },
    {
      id: "perf",
      label: "Performance",
      keywords: ["opcache", "profil", "cache", "xdebug", "performance", "highload"],
    },
    {
      id: "security",
      label: "Security",
      keywords: ["csrf", "xss", "sql injection", "security", "auth", "jwt", "oauth"],
    },
    {
      id: "devops",
      label: "Deploy/Docker",
      keywords: ["docker", "nginx", "php-fpm", "kubernetes", "ci", "cd"],
    },
  ],
  csharp: [
    {
      id: "dotnet",
      label: "C#/.NET",
      keywords: ["c#", "csharp", ".net", "dotnet", "clr", "il"],
    },
    {
      id: "oop",
      label: "OOP/Generics",
      keywords: ["oop", "class", "interface", "inherit", "generic", "delegat", "event"],
    },
    {
      id: "async",
      label: "Async/await",
      keywords: [
        "async",
        "await",
        "task",
        "thread",
        "tpl",
        "deadlock",
        "synchronizationcontext",
      ],
    },
    {
      id: "linq",
      label: "LINQ",
      keywords: ["linq", "ienumerable", "lambda", "expression"],
    },
    {
      id: "aspnet",
      label: "ASP.NET",
      keywords: [
        "asp.net",
        "aspnet",
        "mvc",
        "web api",
        "minimal api",
        "middleware",
        "dependency injection",
      ],
    },
    {
      id: "ef",
      label: "EF Core",
      keywords: ["entity framework", "ef", "ef core", "migration", "dbcontext", "tracking"],
    },
    {
      id: "testing",
      label: "Testing",
      keywords: ["xunit", "nunit", "mstest", "moq", "integration test"],
    },
    {
      id: "micro",
      label: "Microservices",
      keywords: ["microservice", "grpc", "kafka", "rabbit", "docker", "kubernetes"],
    },
    {
      id: "perf",
      label: "Performance",
      keywords: ["gc", "memory", "profil", "span", "stackalloc", "performance"],
    },
  ],
  cpp: [
    {
      id: "core",
      label: "C/C++ Basics",
      keywords: ["c++", "cpp", "c ", "pointers", "указател", "memory", "памят", "stack", "heap"],
    },
    {
      id: "oop",
      label: "OOP/Templates",
      keywords: ["oop", "класс", "виртуаль", "vtable", "template", "шаблон", "stl"],
    },
    {
      id: "stl",
      label: "STL/Containers",
      keywords: ["vector", "map", "unordered", "list", "deque", "string", "stl"],
    },
    {
      id: "memory",
      label: "Memory Management",
      keywords: ["new", "delete", "malloc", "free", "smart pointer", "unique_ptr", "shared_ptr", "raii"],
    },
    {
      id: "concurrency",
      label: "Concurrency",
      keywords: ["thread", "mutex", "atomic", "lock", "condition_variable", "race", "deadlock"],
    },
    {
      id: "build",
      label: "Build/Tooling",
      keywords: ["cmake", "make", "gcc", "clang", "msvc", "linker", "compiler", "сборк"],
    },
    {
      id: "perf",
      label: "Performance",
      keywords: ["perf", "profil", "optimization", "cache", "inline", "branch", "sse", "avx"],
    },
    {
      id: "os",
      label: "OS/Systems",
      keywords: ["linux", "syscall", "socket", "tcp", "udp", "process", "thread", "unix", "posix"],
    },
  ],
  "1c": [
    {
      id: "platform",
      label: "Платформа 1С",
      keywords: [
        "1с",
        "1c",
        "платформ",
        "конфигурац",
        "конфигуратор",
        "управляемые формы",
        "тонкий клиент",
      ],
    },
    {
      id: "lang",
      label: "Язык/Запросы",
      keywords: ["запрос", "скд", "язык запросов", "sql", "выборка", "регист"],
    },
    {
      id: "accounting",
      label: "Учет/Регистры",
      keywords: ["регистр", "накоплен", "бухгалтер", "проводк", "справочник", "документ"],
    },
    {
      id: "integration",
      label: "Интеграции",
      keywords: ["http", "rest", "soap", "webservice", "обмен", "xml", "json", "edi"],
    },
    {
      id: "perf",
      label: "Производительность",
      keywords: ["оптимизац", "индекс", "производитель", "замер", "кэш"],
    },
    {
      id: "devops",
      label: "Внедрение/Обновления",
      keywords: ["обновлен", "релиз", "расширен", "расширение", "хранилище конфигурации"],
    },
    {
      id: "reports",
      label: "Отчеты",
      keywords: ["отчет", "скд", "печатная форма", "макет"],
    },
    {
      id: "security",
      label: "Права/Роли",
      keywords: ["роль", "права", "рлс", "доступ", "безопас"],
    },
  ],
  nodejs: [
    {
      id: "node",
      label: "Node.js Core",
      keywords: ["node", "nodejs", "event loop", "libuv", "stream", "buffer"],
    },
    {
      id: "ts",
      label: "TypeScript",
      keywords: ["typescript", "ts"],
    },
    {
      id: "frameworks",
      label: "Frameworks",
      keywords: ["express", "nestjs", "nest", "koa", "fastify"],
    },
    {
      id: "async",
      label: "Async",
      keywords: ["promise", "async", "await", "callback", "microtask", "queue"],
    },
    {
      id: "db",
      label: "DB/ORM",
      keywords: [
        "sql",
        "postgres",
        "mysql",
        "mongodb",
        "prisma",
        "typeorm",
        "mongoose",
        "migration",
      ],
    },
    {
      id: "api",
      label: "API",
      keywords: ["rest", "api", "graphql", "websocket", "ws"],
    },
    {
      id: "testing",
      label: "Testing",
      keywords: ["jest", "vitest", "mocha", "chai", "supertest", "e2e"],
    },
    {
      id: "devops",
      label: "Deploy/Docker",
      keywords: ["docker", "kubernetes", "pm2", "nginx", "ci", "cd"],
    },
    {
      id: "security",
      label: "Security",
      keywords: ["jwt", "oauth", "csrf", "xss", "rate limit", "security"],
    },
  ],
  ios: [
    {
      id: "swift",
      label: "Swift",
      keywords: ["swift", "optional", "generics", "protocol", "extension", "closure", "async", "await"],
    },
    {
      id: "uikit",
      label: "UIKit",
      keywords: ["uikit", "autolayout", "storyboard", "xib", "viewcontroller", "constraint"],
    },
    {
      id: "swiftui",
      label: "SwiftUI",
      keywords: ["swiftui", "@state", "@binding", "@observedobject", "combine"],
    },
    {
      id: "arch",
      label: "Architecture",
      keywords: ["mvc", "mvvm", "vip", "clean", "coordinator", "архитектур"],
    },
    {
      id: "network",
      label: "Networking",
      keywords: ["urlsession", "http", "rest", "api", "json", "codable"],
    },
    {
      id: "storage",
      label: "Storage",
      keywords: ["coredata", "realm", "userdefaults", "keychain", "sqlite"],
    },
    {
      id: "multithread",
      label: "Concurrency",
      keywords: ["gcd", "dispatch", "operationqueue", "thread", "race"],
    },
    {
      id: "testing",
      label: "Testing",
      keywords: ["xctest", "ui test", "unit test", "snapshot"],
    },
    {
      id: "release",
      label: "Build/Release",
      keywords: [
        "xcode",
        "cocoapods",
        "spm",
        "swift package",
        "testflight",
        "app store",
        "provisioning",
      ],
    },
  ],
  android: [
    {
      id: "kotlin",
      label: "Kotlin",
      keywords: ["kotlin", "coroutines", "suspend", "flow"],
    },
    {
      id: "java",
      label: "Java",
      keywords: ["java", "jvm"],
    },
    {
      id: "sdk",
      label: "Android SDK",
      keywords: ["android", "sdk", "activity", "fragment", "lifecycle", "intent", "manifest"],
    },
    {
      id: "ui",
      label: "UI",
      keywords: [
        "compose",
        "jetpack compose",
        "xml",
        "view",
        "recycler",
        "constraintlayout",
      ],
    },
    {
      id: "arch",
      label: "Architecture",
      keywords: ["mvvm", "mvp", "clean", "di", "dagger", "hilt", "koin"],
    },
    {
      id: "network",
      label: "Networking",
      keywords: ["retrofit", "okhttp", "rest", "api", "json"],
    },
    {
      id: "storage",
      label: "Storage",
      keywords: ["room", "sqlite", "datastore", "sharedpreferences"],
    },
    {
      id: "testing",
      label: "Testing",
      keywords: ["junit", "espresso", "instrumentation", "ui test"],
    },
    {
      id: "build",
      label: "Build/CI",
      keywords: ["gradle", "agp", "ci", "cd", "firebase", "crashlytics"],
    },
  ],
  flutter: [
    {
      id: "dart",
      label: "Dart",
      keywords: ["dart", "async", "future", "stream"],
    },
    {
      id: "flutter",
      label: "Flutter UI",
      keywords: ["flutter", "widget", "stateful", "stateless", "buildcontext", "render"],
    },
    {
      id: "state",
      label: "State Management",
      keywords: ["bloc", "provider", "riverpod", "redux", "mobx", "state"],
    },
    {
      id: "nav",
      label: "Navigation",
      keywords: ["navigator", "routes", "deep link"],
    },
    {
      id: "network",
      label: "Networking",
      keywords: ["dio", "http", "rest", "api", "json"],
    },
    {
      id: "storage",
      label: "Storage",
      keywords: ["sharedpreferences", "hive", "sqflite", "isar"],
    },
    {
      id: "testing",
      label: "Testing",
      keywords: ["flutter test", "widget test", "integration test", "mockito"],
    },
    {
      id: "platform",
      label: "Platform/Native",
      keywords: ["platform channel", "ios", "android", "swift", "kotlin", "ffi"],
    },
    {
      id: "build",
      label: "Build/Release",
      keywords: ["pubspec", "build", "release", "app store", "google play", "ci", "cd"],
    },
  ],
  unity: [
    {
      id: "csharp",
      label: "C#",
      keywords: ["c#", "unity", "mono", ".net"],
    },
    {
      id: "engine",
      label: "Engine Basics",
      keywords: ["gameobject", "component", "scene", "prefab", "transform"],
    },
    {
      id: "physics",
      label: "Physics",
      keywords: ["rigidbody", "collider", "physics", "raycast", "forces"],
    },
    {
      id: "render",
      label: "Rendering",
      keywords: [
        "shader",
        "material",
        "render",
        "urp",
        "hdrp",
        "lighting",
        "post-processing",
      ],
    },
    {
      id: "perf",
      label: "Optimization",
      keywords: ["optimization", "fps", "profil", "gc", "draw call", "batching"],
    },
    {
      id: "ui",
      label: "UI",
      keywords: ["canvas", "uGUI", "ui toolkit", "recttransform"],
    },
    {
      id: "input",
      label: "Input",
      keywords: ["input system", "touch", "keyboard", "mouse", "controller"],
    },
    {
      id: "assets",
      label: "Assets/Pipeline",
      keywords: ["asset", "addressables", "resources", "bundl", "import", "pipeline"],
    },
    {
      id: "net",
      label: "Networking",
      keywords: ["multiplayer", "netcode", "photon", "mirror", "rpc"],
    },
  ],
  devops: [
    {
      id: "linux",
      label: "Linux",
      keywords: ["linux", "bash", "shell", "systemd", "fs", "permissions"],
    },
    {
      id: "docker",
      label: "Docker",
      keywords: ["docker", "dockerfile", "compose", "container", "image"],
    },
    {
      id: "k8s",
      label: "Kubernetes",
      keywords: ["kubernetes", "k8s", "helm", "ingress", "service", "pod", "deployment"],
    },
    {
      id: "ci",
      label: "CI/CD",
      keywords: ["ci", "cd", "gitlab", "github actions", "jenkins", "pipeline"],
    },
    {
      id: "iac",
      label: "IaC",
      keywords: ["terraform", "ansible", "cloudformation", "iac"],
    },
    {
      id: "cloud",
      label: "Cloud",
      keywords: ["aws", "gcp", "azure", "yandex cloud", "cloud", "s3", "ec2"],
    },
    {
      id: "observ",
      label: "Monitoring/Logs",
      keywords: [
        "prometheus",
        "grafana",
        "elk",
        "loki",
        "jaeger",
        "opentelemetry",
        "monitoring",
        "logging",
      ],
    },
    {
      id: "net",
      label: "Networking",
      keywords: ["dns", "http", "tcp", "udp", "load balancer", "nginx", "iptables", "vpn"],
    },
    {
      id: "sec",
      label: "Security",
      keywords: ["vault", "secrets", "tls", "ssl", "iam", "security"],
    },
  ],
  "data-engineer": [
    {
      id: "etl",
      label: "ETL/ELT",
      keywords: ["etl", "elt", "pipeline", "batch", "ingest", "extract", "transform", "load"],
    },
    {
      id: "dwh",
      label: "DWH/Modeling",
      keywords: [
        "dwh",
        "warehouse",
        "star schema",
        "snowflake schema",
        "dim",
        "fact",
        "модель данных",
      ],
    },
    {
      id: "sql",
      label: "SQL",
      keywords: ["sql", "join", "window", "cte", "index", "partition"],
    },
    {
      id: "spark",
      label: "Spark/Big Data",
      keywords: ["spark", "pyspark", "hadoop", "hive", "presto", "trino"],
    },
    {
      id: "stream",
      label: "Streaming",
      keywords: ["kafka", "stream", "flink", "spark streaming", "cdc", "debezium"],
    },
    {
      id: "orchestration",
      label: "Orchestration",
      keywords: ["airflow", "dag", "luigi", "prefect", "оркестрац"],
    },
    {
      id: "storage",
      label: "Storage",
      keywords: ["s3", "hdfs", "parquet", "orc", "delta lake", "iceberg"],
    },
    {
      id: "quality",
      label: "Data Quality",
      keywords: ["quality", "dq", "validation", "great expectations", "lineage"],
    },
    {
      id: "devops",
      label: "Deploy",
      keywords: ["docker", "kubernetes", "ci", "cd"],
    },
  ],
  qa: [
    {
      id: "basics",
      label: "Основы тестирования",
      keywords: ["тестирован", "qa", "quality", "verification", "validation"],
    },
    {
      id: "testdesign",
      label: "Тест-дизайн",
      keywords: [
        "test design",
        "тест-дизайн",
        "эквивалент",
        "границ",
        "pairwise",
        "decision table",
        "state transition",
      ],
    },
    {
      id: "testtypes",
      label: "Виды тестирования",
      keywords: [
        "smoke",
        "sanity",
        "regression",
        "functional",
        "non-functional",
        "нагрузоч",
        "performance",
      ],
    },
    {
      id: "artifacts",
      label: "Артефакты",
      keywords: [
        "test case",
        "тест-кейс",
        "чек-лист",
        "checklist",
        "bug report",
        "баг-репорт",
        "test plan",
      ],
    },
    {
      id: "api",
      label: "API/HTTP",
      keywords: [
        "http",
        "rest",
        "api",
        "status code",
        "header",
        "get",
        "post",
        "put",
        "delete",
        "soap",
      ],
    },
    {
      id: "sql",
      label: "SQL/DB",
      keywords: ["sql", "join", "select", "where", "index", "transaction"],
    },
    {
      id: "tools",
      label: "Инструменты",
      keywords: ["postman", "swagger", "jira", "testrail", "charles", "fiddler"],
    },
    {
      id: "process",
      label: "Процессы",
      keywords: ["agile", "scrum", "kanban", "stlc", "sdlc", "severity", "priority"],
    },
  ],
  "qa-automation": [
    {
      id: "lang",
      label: "Язык программирования",
      keywords: ["java", "python", "javascript", "c#", "kotlin"],
    },
    {
      id: "framework",
      label: "Фреймворки",
      keywords: ["selenium", "playwright", "cypress", "appium", "webdriver", "selenide"],
    },
    {
      id: "patterns",
      label: "Паттерны автотестов",
      keywords: ["page object", "pageobject", "bdd", "cucumber", "gherkin", "tdd"],
    },
    {
      id: "api",
      label: "API tests",
      keywords: ["rest-assured", "supertest", "http client", "api test", "postman"],
    },
    {
      id: "ci",
      label: "CI/CD",
      keywords: ["ci", "cd", "jenkins", "gitlab", "github actions", "pipeline"],
    },
    {
      id: "report",
      label: "Отчеты/Allure",
      keywords: ["allure", "report", "logging", "screenshot", "video"],
    },
    {
      id: "stability",
      label: "Стабильность",
      keywords: ["flaky", "ретраи", "wait", "timeout", "synchronization", "stabil"],
    },
    {
      id: "parallel",
      label: "Параллелизация",
      keywords: ["parallel", "grid", "selenium grid", "docker", "kubernetes"],
    },
    {
      id: "unit",
      label: "Unit tests",
      keywords: ["unit test", "junit", "pytest", "jest", "mock"],
    },
  ],
  datascience: [
    {
      id: "ml",
      label: "Machine Learning",
      keywords: ["ml", "machine learning", "классиф", "регресс", "clustering", "метрик", "loss"],
    },
    {
      id: "stats",
      label: "Статистика",
      keywords: [
        "stat",
        "статист",
        "p-value",
        "hypothesis",
        "доверит",
        "дисперс",
        "variance",
      ],
    },
    {
      id: "python",
      label: "Python stack",
      keywords: ["python", "pandas", "numpy", "sklearn", "scikit", "matplotlib", "seaborn"],
    },
    {
      id: "dl",
      label: "Deep Learning",
      keywords: [
        "neural",
        "нейрон",
        "pytorch",
        "tensorflow",
        "keras",
        "cnn",
        "rnn",
        "transformer",
      ],
    },
    {
      id: "nlp",
      label: "NLP",
      keywords: ["nlp", "bert", "token", "embedding", "language model", "llm"],
    },
    {
      id: "cv",
      label: "Computer Vision",
      keywords: ["cv", "vision", "image", "cnn", "augmentation", "opencv"],
    },
    {
      id: "experiment",
      label: "Эксперименты",
      keywords: [
        "cross-validation",
        "cv",
        "train",
        "test",
        "overfit",
        "underfit",
        "a/b",
        "эксперимент",
      ],
    },
    {
      id: "deploy",
      label: "ML in prod",
      keywords: [
        "mlops",
        "deploy",
        "serving",
        "onnx",
        "docker",
        "kubernetes",
        "monitoring",
        "drift",
      ],
    },
  ],
  "data-analyst": [
    {
      id: "sql",
      label: "SQL",
      keywords: ["sql", "join", "group by", "window", "cte", "subquery"],
    },
    {
      id: "dash",
      label: "BI/Dashboards",
      keywords: ["tableau", "power bi", "metabase", "superset", "дашборд", "bi"],
    },
    {
      id: "metrics",
      label: "Метрики",
      keywords: ["kpi", "метрик", "retention", "arpu", "ltv", "cac", "conversion", "воронк"],
    },
    {
      id: "viz",
      label: "Визуализация",
      keywords: ["visual", "chart", "график", "plot", "data studio", "look"],
    },
    {
      id: "product",
      label: "Продуктовая аналитика",
      keywords: ["cohort", "когорт", "a/b", "аб тест", "experiment", "гипотез"],
    },
    {
      id: "excel",
      label: "Excel/Sheets",
      keywords: ["excel", "google sheets", "pivot", "vlookup", "xlookup", "power query"],
    },
    {
      id: "python",
      label: "Python for analysis",
      keywords: ["python", "pandas", "numpy", "jupyter"],
    },
    {
      id: "data",
      label: "Сбор данных",
      keywords: ["event", "tracking", "utm", "ga", "amplitude", "mixpanel", "etl"],
    },
  ],
  "business-analyst": [
    {
      id: "req",
      label: "Требования",
      keywords: [
        "requirement",
        "требован",
        "user story",
        "use case",
        "acceptance criteria",
        "ac",
      ],
    },
    {
      id: "process",
      label: "Процессы",
      keywords: ["bpmn", "as-is", "to-be", "process", "бизнес-процесс"],
    },
    {
      id: "docs",
      label: "Документация",
      keywords: ["spec", "тз", "brd", "srs", "confluence", "doc"],
    },
    {
      id: "elicitation",
      label: "Сбор требований",
      keywords: ["интервью", "workshop", "стейкхолдер", "facilitation", "question"],
    },
    {
      id: "prior",
      label: "Приоритизация",
      keywords: ["moscow", "rice", "kano", "priority", "roadmap"],
    },
    {
      id: "comm",
      label: "Коммуникации",
      keywords: ["communication", "conflict", "align", "presentation", "переговор"],
    },
    {
      id: "domain",
      label: "Домен/Контекст",
      keywords: ["domain", "контекст", "glossary", "термин"],
    },
    {
      id: "data",
      label: "Данные/Метрики",
      keywords: ["kpi", "метрик", "sql", "report", "дашборд"],
    },
  ],
  "system-analyst": [
    {
      id: "api",
      label: "API/Интеграции",
      keywords: ["api", "rest", "soap", "grpc", "integration", "интеграц", "swagger", "openapi"],
    },
    {
      id: "data",
      label: "Модели данных",
      keywords: ["erd", "entity", "relation", "нормализац", "sql", "schema", "модель данных"],
    },
    {
      id: "arch",
      label: "Архитектура",
      keywords: ["архитектур", "компонент", "монолит", "микросервис", "event", "bus"],
    },
    {
      id: "docs",
      label: "Документация",
      keywords: ["spec", "srs", "тз", "конфлюенс", "uml", "diagram"],
    },
    {
      id: "uml",
      label: "UML/Диаграммы",
      keywords: ["uml", "sequence", "class diagram", "activity", "component", "диаграмм"],
    },
    {
      id: "nonfunc",
      label: "НФТ",
      keywords: ["non-functional", "sla", "slo", "availability", "performance", "security", "нфт"],
    },
    {
      id: "msg",
      label: "Очереди",
      keywords: ["kafka", "rabbit", "queue", "nats", "event"],
    },
    {
      id: "testing",
      label: "Тестирование/Приемка",
      keywords: ["acceptance", "at", "uat", "тест-кейс", "приемк"],
    },
  ],
  "data-analytics": [
    {
      id: "sql",
      label: "SQL",
      keywords: ["sql", "join", "window", "group by"],
    },
    {
      id: "metrics",
      label: "Метрики",
      keywords: ["kpi", "метрик", "retention", "conversion", "воронк", "cohort", "когорт"],
    },
    {
      id: "bi",
      label: "BI",
      keywords: ["tableau", "power bi", "metabase", "superset", "дашборд"],
    },
    {
      id: "ab",
      label: "A/B тесты",
      keywords: ["a/b", "аб", "experiment", "гипотез", "p-value"],
    },
    {
      id: "etl",
      label: "ETL",
      keywords: ["etl", "pipeline", "airflow", "dwh"],
    },
    {
      id: "python",
      label: "Python",
      keywords: ["python", "pandas", "numpy", "jupyter"],
    },
    {
      id: "tracking",
      label: "Трекинг",
      keywords: ["event", "tracking", "utm", "ga", "amplitude", "mixpanel"],
    },
    {
      id: "story",
      label: "Data storytelling",
      keywords: ["story", "insight", "презентац", "вывод"],
    },
  ],
  "product-analytics": [
    {
      id: "metrics",
      label: "Метрики продукта",
      keywords: [
        "retention",
        "arpu",
        "ltv",
        "cac",
        "conversion",
        "воронк",
        "north star",
        "ns metric",
      ],
    },
    {
      id: "cohort",
      label: "Когорты",
      keywords: ["cohort", "когорт", "retention curve"],
    },
    {
      id: "ab",
      label: "A/B тесты",
      keywords: ["a/b", "experiment", "p-value", "alpha", "beta", "uplift", "mde"],
    },
    {
      id: "funnel",
      label: "Воронки",
      keywords: ["funnel", "воронк", "step", "conversion"],
    },
    {
      id: "seg",
      label: "Сегментация",
      keywords: ["segment", "segmentation", "сегмент", "cohort"],
    },
    {
      id: "tracking",
      label: "События/Трекинг",
      keywords: ["event", "tracking", "amplitude", "mixpanel", "ga", "utm"],
    },
    {
      id: "sql",
      label: "SQL",
      keywords: ["sql", "join", "window", "cte"],
    },
    {
      id: "dash",
      label: "Дашборды",
      keywords: ["dashboard", "дашборд", "bi", "tableau", "power bi", "metabase"],
    },
    {
      id: "unit",
      label: "Юнит-экономика",
      keywords: ["unit economics", "юнит", "margin", "arpu", "ltv"],
    },
  ],
  pm: [
    {
      id: "delivery",
      label: "Delivery",
      keywords: ["delivery", "доставка", "release", "релиз", "roadmap", "timeline", "план"],
    },
    {
      id: "methods",
      label: "Методологии",
      keywords: ["scrum", "kanban", "agile", "waterfall", "safe"],
    },
    {
      id: "planning",
      label: "Планирование",
      keywords: ["estimate", "оценк", "gantt", "wbs", "scope", "backlog", "спринт"],
    },
    {
      id: "risk",
      label: "Риски",
      keywords: ["risk", "риски", "mitigation", "issue", "impediment"],
    },
    {
      id: "stake",
      label: "Стейкхолдеры",
      keywords: ["stakeholder", "стейкхолдер", "communication", "report", "status"],
    },
    {
      id: "team",
      label: "Команда",
      keywords: ["team", "команд", "resource", "роли", "motivation", "конфликт"],
    },
    {
      id: "tools",
      label: "Инструменты",
      keywords: ["jira", "confluence", "trello", "notion"],
    },
    {
      id: "quality",
      label: "Качество",
      keywords: ["qa", "test", "acceptance", "definition of done", "dod"],
    },
    {
      id: "budget",
      label: "Бюджет/Контракт",
      keywords: ["budget", "бюджет", "contract", "смета", "invoice"],
    },
  ],
  product: [
    {
      id: "discovery",
      label: "Discovery",
      keywords: ["discovery", "custdev", "customer development", "интервью", "problem"],
    },
    {
      id: "strategy",
      label: "Стратегия",
      keywords: ["strategy", "vision", "north star", "okrs", "okr", "roadmap"],
    },
    {
      id: "hyp",
      label: "Гипотезы",
      keywords: ["hypothesis", "гипотез", "experiment", "mvp", "iterat"],
    },
    {
      id: "metrics",
      label: "Метрики роста",
      keywords: ["growth", "retention", "activation", "conversion", "arpu", "ltv", "metric"],
    },
    {
      id: "pricing",
      label: "Монетизация",
      keywords: ["pricing", "цена", "монетизац", "paywall", "freemium"],
    },
    {
      id: "analytics",
      label: "Аналитика",
      keywords: ["a/b", "cohort", "funnel", "segmentation", "analytics", "sql"],
    },
    {
      id: "delivery",
      label: "Delivery/Команда",
      keywords: ["delivery", "backlog", "scrum", "kanban", "team"],
    },
    {
      id: "market",
      label: "Рынок/Конкуренты",
      keywords: ["market", "конкурент", "позиционирован", "go-to-market", "gtm"],
    },
    {
      id: "stake",
      label: "Стейкхолдеры",
      keywords: ["stakeholder", "презентац", "коммуникац", "align"],
    },
  ],
};

export function getTrackSkillFilters(slug: string): TrackSkillFilter[] {
  return TRACK_SKILL_MAP[slug] ?? [];
}
